### ISSUE TITLE
Disappreance of data after entity ingestion

### ISSUE THREAD

**Issue by aditya-manit** [goldenrecursion/godel#34]
**Describe the bug**
All structured data disappeared after entity ingestion. When an entity is pushed through godel, it appears for sometime on the dapp and after sometime all data disappeared.

**To Reproduce**
1. I used the godel to push entities
2. Copy the entity link, check it on dapp it will appear there
3. After sometime all structured data will disappear

**Expected behavior**
Entity ingestion should persist

**Screenshots**
You can see all the structured data here: https://i.ibb.co/0VYrXHZ/Screenshot-2022-10-29-at-4-07-34-PM.png check this entity link after sometime everything will disappear: https://dapp.golden.xyz/entity/f2c98575-0809-4011-97fc-787017b47b71

**Desktop (please complete the following information):**
I used the latest version of godel

**Additional context**
I have reported it on discord many times over the last week but no one is paying any attention. I spend days over fetching dataset and then writing script, the amount of entities I have pushed should make me come at the top of the leaderboard, but due to this bug no past activity records appears for my wallet. The worst part is team doesn't care and nobody is not paying any attentions to it. Looks like I just wasted my time, never coming back to golden if this github issues gets ignored too.

Here are my past messages on discord:
https://discord.com/channels/900818355315961876/957045897810821201/1034736485544509501
https://discord.com/channels/900818355315961876/1034736485544509501/1035383247997239436
https://discord.com/channels/900818355315961876/1034736485544509501/1035390410828304415
https://discord.com/channels/900818355315961876/1034736485544509501/1035393995913826314
https://discord.com/channels/900818355315961876/1034736485544509501/1035681686756798554
https://discord.com/channels/900818355315961876/1034736485544509501/1035780739079352320
https://discord.com/channels/900818355315961876/1034736485544509501/1035828937449807932
https://discord.com/channels/900818355315961876/1034736485544509501/1035866146525696041
https://discord.com/channels/900818355315961876/957045897810821201/1035870912492343306
https://discord.com/channels/900818355315961876/957045897810821201/1036098383196209193

Fix the issue and fix my testnet point count

**Comment by aditya-manit** [comment]
Here is the a csv of all the 8843 entities that I have pushed twice and got the same result. The first time I didn't save all the entity IDs but the second time I did.
[all_pushed_entities.csv](https://github.com/goldenrecursion/godel/files/9895208/all_pushed_entities.csv)

This is the proof of my participant and I hope to get my score correct

**Comment by aychang95** [comment]
@aditya-manit 
Thanks for bringing this to our attention and expanding on your issues in discord!
We've been investigating and working on a solution to the issues you've been facing which have been a bit uncommon due to you being a recent programmatic user along with the amount of data you've been submitting.

The core issue here is that your wallet account is brand new so you've been at 0 points. Your submissions have been placed on a "pause" state due to anti-gaming mechanisms that have been put in place. 

This should not be an issue as you build up points from verification and data submission tasks, but we're working on a solution to prevent this specific case from happening. I'll keep this issue open until it's addressed

**Comment by aditya-manit** [comment]
Got it, appreciate you guys talking time to look into it

**Comment by aditya-manit** [comment]
Just checking in if they is update on this

**Comment by aychang95** [comment]
@aditya-manit 
Yes, we're rolling out an initial points reward for programmatic users who are submitting accurate bulk data like yourself. This should unblock you on this issue, but I suggest you still try to verify triples programmatically or via. the dApp to see some organic points build up from 0.

I'll keep this open until this solution reflects for you and other users

**Comment by aditya-manit** [comment]
Appreciate it !
Yeah I would love to validate some triplets but there is no way to filter triplets that one wants to validate, if there could be a feature like this, I can gather datasets and write a scripts for it as well, anyways will try to validate some through the apps.

**Comment by aychang95** [comment]
@aditya-manit 
Closing since addressed!

**Comment by aditya-manit** [comment]
I just finished uploading everything again and looks like it is same as before, here are some links
https://dapp.golden.xyz/entity/a6b319a5-3e9e-41f8-8cc5-d2d5cd6508f1
https://dapp.golden.xyz/entity/8562feac-eb28-4d31-8ece-56c743a098b6
This was the 4th time I uploaded all the data

Can we reopen the issue ?

**Comment by aditya-manit** [comment]
> @aditya-manit Closing since addressed!

It is not addressed, my score isn't fixed and I am having follow up issues on this, none of my submission has gotten accepted.

<img width="895" alt="Screenshot_2022-12-31_at_1 10 08_PM" src="https://user-images.githubusercontent.com/40714633/210129497-feaa5b41-4935-4c41-8443-a9ecc78f748e.png">


Here is an example: https://dapp.golden.xyz/entity/63921549-86f4-4f29-9de3-9d883267edc7


Could you reopen the issues and address it @aychang95
