### ISSUE TITLE
INT max should be increased

### ISSUE THREAD

**Issue by aditya-manit** [goldenrecursion/godel#35]
**Describe the bug**
INT object value can store upto maximum of 2,147,483,647 -> which is not sufficient to fulfil all use cases.

**Comment by aychang95** [comment]
Moved the discussion over to our forums on this topic: https://forum.golden.xyz/t/int-object-values-are-maxed-out-at-2-147-483-647/482

This is a valid API format point that we should discuss on a predicate-level.
